### ISSUE TITLE
"location name" is missing in API response

### ISSUE THREAD

**Issue by neeg** [apixu/apixu-php#18]
**It's a general problem of the API not specific to this one here. But I haven't found another channel where I could report the bug. I didn't get any feedback via the general contact form.**

When searching current weather by Latitude / Longitude, the location does not have any name, region or country values:

Example with Lat/Lng for Paris:
http://api-cdn.apixu.com/v1/current.json?key=xxx&q=48.87,2.33
```javascript
{
    "location": {
        "name": "",
        "region": "",
        "country": "",
        "lat": 48.87,
        "lon": 2.33,
        "tz_id": "Europe/Paris",
        "localtime_epoch": 1567420302,
        "localtime": "2019-09-08 12:31"
    },
    [...]
```

When searching by name, everything is fine:

http://api-cdn.apixu.com/v1/current.json?key=xxx&q=Paris
```javascript
{
    "location": {
        "name": "Paris",
        "region": "Ile-de-France",
        "country": "France",
        "lat": 48.87,
        "lon": 2.33,
        "tz_id": "Europe/Paris",
        "localtime_epoch": 1567420090,
        "localtime": "2019-09-08 12:28"
    },
   [...]
```

It'd be great if you could fix this issue.

**Comment by andreiavrammsd** [comment]
Hello,

Apixu API will be moved to weatherstack, please see here:
https://github.com/apilayer/weatherstack#readme
