### ISSUE TITLE
ApiXU Telephone Interface

### ISSUE THREAD

**Issue by wardmundy** [apixu/apixu-php#3]
We've incorporated the ApiXU PHP components into a new Worldwide Weather application suitable for deployment with Asterisk and 3CX PBX servers so that users can call a predefined extension and retrieve weather reports by telephone. Most of our applications are released as GPL2 code; however, the ApiXU script (nv-worldwide-weather.php) is released pursuant to The MIT License as required by the terms of the original ApiXU license. Everyone is more than welcome to download the components and read the tutorial on Nerd Vittles: http://nerdvittles.com/?p=24135

**Comment by andreiavrammsd** [comment]
How does this affect you?

Thank you!

**Comment by andreiavrammsd** [comment]
Closing for being stale. Please come back any time with additional info if needed.
