### ISSUE TITLE
composer dependency andreiavrammsd/serializer stuck to version 0.4

### ISSUE THREAD

**Issue by jmfeurprier** [apixu/apixu-php#7]
Even though andreiavrammsd/serializer 0.5 and 0.5.1 are released and seem to be compatible with apixu/apixu-php (if using semantic versionning) , it remains stuck at version 0.4

In file `composer.json`, the version requirement is `^0.4` which means usable versions are `>=0.4.0` and `<0.5.0`

Versions 0.5.x could become usable by altering `composer.json` as follows:

`^0.4.0` or `~0.4` which mean usable versions are `>=0.4.0` and `<1.0.0`

Refs for "Next Significant Release Operators" behaviors:
- https://getcomposer.org/doc/articles/versions.md#tilde-version-range-
- https://getcomposer.org/doc/articles/versions.md#caret-version-range-

Thanks !

**Comment by andreiavrammsd** [comment]
@jmfeurprier, thank you for noting the issue!

As long as serializer is under v1, I would like to keep the dependency around the minor version, so I've just upgraded it to v0.5
